import { NextRequest, NextResponse } from "next/server";
import { consumeOTT } from "@/lib/dingtalk-ott-store";
import { decode } from "next-auth/jwt";

const SESSION_MAX_AGE = 30 * 24 * 60 * 60;

function getBaseUrl(): string {
  return (process.env.NEXTAUTH_URL || "http://localhost:8060").replace(
    /\/$/,
    ""
  );
}

// This endpoint consumes a one-time token (OTT) generated by the workbench
// route and establishes a session. It's designed to work around DingTalk
// mobile WebView's unreliable cookie persistence across navigations.
//
// Flow: workbench (POST) → 302 to /exchange?ott=xxx (GET) → set cookie → redirect to /
export async function GET(request: NextRequest) {
  const ott = request.nextUrl.searchParams.get("ott");

  if (!ott) {
    console.warn("[dingtalk] exchange: missing ott parameter");
    return NextResponse.redirect(new URL("/login?error=dingtalk_auth_failed", request.url));
  }

  const entry = consumeOTT(ott);
  if (!entry) {
    console.warn("[dingtalk] exchange: invalid or expired OTT");
    return NextResponse.redirect(new URL("/login?error=dingtalk_auth_failed", request.url));
  }

  console.log("[dingtalk] exchange: valid OTT for user:", entry.userId, entry.userName);

  // Validate the session token before setting it
  const decoded = await decode({
    token: entry.sessionToken,
    secret: process.env.NEXTAUTH_SECRET!,
  });

  if (!decoded) {
    console.error("[dingtalk] exchange: invalid session token");
    return NextResponse.redirect(new URL("/login?error=dingtalk_auth_failed", request.url));
  }

  const baseUrl = getBaseUrl();

  // Strategy 1: Return HTML with document.cookie + localStorage backup
  // This works even if Set-Cookie headers are dropped by the WebView
  const cookieName = "next-auth.session-token";
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>正在登录...</title>
<script src="https://g.alicdn.com/code/npm/@ali/dingtalk-h5-remote-debug/0.1.3/index.js"></script>
</head>
<body style="display:flex;justify-content:center;align-items:center;height:100vh;font-family:sans-serif">
<div style="text-align:center">
<p>登录成功，正在跳转...</p>
<p id="dbg" style="font-size:12px;color:#999"></p>
</div>
<script>
(function(){
  var token = ${JSON.stringify(entry.sessionToken)};
  var name = ${JSON.stringify(cookieName)};
  var dbg = document.getElementById("dbg");

  function log(m){ try{ dbg.textContent += m + " | "; console.log("[dt-exchange]", m); }catch(e){} }

  // 1. Store in localStorage as ultimate fallback
  try { localStorage.setItem("dt_session_token", token); log("localStorage OK"); } catch(e) { log("localStorage FAIL:" + e.message); }

  // 2. Clear old cookies
  document.cookie = name + "=; path=/; max-age=0";
  document.cookie = name + "=; path=/; max-age=0; domain=doc.idrl.top";

  // 3. Set cookie with SameSite=None for cross-navigation persistence
  document.cookie = name + "=" + token + "; path=/; max-age=${SESSION_MAX_AGE}; SameSite=None; Secure";
  log("cookie set");

  // 4. Verify cookie was actually set
  var cookieSet = document.cookie.indexOf(name + "=") !== -1;
  log("cookie verify:" + (cookieSet ? "YES" : "NO"));

  // 5. Redirect — include OTT-replacement param so proxy can read localStorage token
  setTimeout(function(){
    var target = ${JSON.stringify(baseUrl + "/")};
    // If cookie wasn't set, use a URL param to signal proxy to look for localStorage
    if (!cookieSet) {
      target += "?_dts=1";
    }
    log("redirect to:" + target);
    window.location.href = target;
  }, 1500);
})();
</script>
</body></html>`;

  const response = new NextResponse(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });

  // Also set via Set-Cookie header (may work in some WebView implementations)
  response.cookies.set(cookieName, entry.sessionToken, {
    httpOnly: false,
    secure: true,
    sameSite: "none",
    path: "/",
    maxAge: SESSION_MAX_AGE,
  });

  return response;
}
